FROM jenkins/jenkins:lts

USER root

RUN apt-get update && \
    apt-get install -y docker-compose wget unzip && \
    # Installer JUSTE docker CLI (pas le daemon!)
    curl -fsSL https://download.docker.com/linux/static/stable/x86_64/docker-24.0.0.tgz | tar xz && \
    mv docker/docker /usr/local/bin/ && \
    rm -rf docker && \
    wget -O /tmp/sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.15.0.6499-linux.zip && \
    unzip /tmp/sonar-scanner.zip -d /opt && \
    ln -s /opt/sonar-scanner-5.15.0.6499-linux/bin/sonar-scanner /usr/local/bin/sonar-scanner && \
    rm /tmp/sonar-scanner.zip && \
    apt-get clean && rm -rf /var/lib/apt/lists/*