
sonar.projectKey=anoors_portfolio_react
sonar.projectName=Portfolio React
sonar.sources=backend,src
sonar.tests=backend/tests,src/tests
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/backend/node_modules/**,**/backend/packages/**
sonar.sourceEncoding=UTF-8

# Configuration pour les tests unitaires et la couverture de code
sonar.javascript.lcov.reportPaths=coverage/lcov.info
