sonar.projectKey=anoors_portfolio_react
sonar.projectName=Portfolio React

# Sources analysées
sonar.sources=src,backend

# Encodage
sonar.sourceEncoding=UTF-8

# Exclusions
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**

# Tests React
sonar.tests=src

# Couverture frontend React
# sonar.javascript.lcov.reportPaths=coverage/lcov.info